# Generated by Django 5.0.3 on 2024-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0005_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('gstin', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
                ('country', models.CharField(max_length=520)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
