# Generated by Django 5.0.3 on 2024-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=500)),
                ('to_company', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('amnount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OutflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('to_company', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('amnount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
