# Generated by Django 5.0.3 on 2024-04-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0007_inflowtransaction_outflowtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflowtransaction',
            old_name='amnount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='outflowtransaction',
            old_name='amnount',
            new_name='amount',
        ),
    ]
