# Generated by Django 5.0.3 on 2024-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0008_rename_amnount_inflowtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
