# Generated by Django 5.0.3 on 2024-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0011_approvedinflowtransaction_approvedoutflowtransaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedInflowTransaction',
        ),
        migrations.DeleteModel(
            name='ApprovedOutflowTransaction',
        ),
        migrations.DeleteModel(
            name='RejectedInflowTransaction',
        ),
        migrations.DeleteModel(
            name='RejectedOutflowTransaction',
        ),
    ]
