# Generated by Django 5.0.3 on 2024-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0015_alter_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflowtransaction',
            name='to_company',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
