# Generated by Django 5.0.3 on 2024-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0016_alter_outflowtransaction_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedinflowtransaction',
            name='Return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvedinflowtransaction',
            name='Return_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='approvedinflowtransaction',
            name='Return_date',
            field=models.DateField(null=True),
        ),
    ]
