# Generated by Django 5.0.3 on 2024-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0017_approvedinflowtransaction_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedinflowtransaction',
            name='Return',
        ),
        migrations.RemoveField(
            model_name='approvedinflowtransaction',
            name='Return_amount',
        ),
        migrations.RemoveField(
            model_name='approvedinflowtransaction',
            name='Return_date',
        ),
        migrations.AddField(
            model_name='approvedoutflowtransaction',
            name='Return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvedoutflowtransaction',
            name='Return_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='approvedoutflowtransaction',
            name='Return_date',
            field=models.DateField(null=True),
        ),
    ]
